# Source: Genesis/charts/bdlstudio/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3rd-party-app-cancer
  labels:
    app: 3rd-party-app-cancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 3rd-party-app-cancer
  template:
    metadata:
      labels:
        app: 3rd-party-app-cancer
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
      - name: 3rd-party-app-cancer
        image: sncap/3rd_party_app_cancer:v1.3
        resources:
          limits:
            cpu: 400m
            memory: 1000Mi
          requests:
            cpu: 400m
            memory: 500Mi
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: 3rd-party-app-cancer
spec:
  scaleTargetRef:  # 스케일 아웃할 타겟 설정
    apiVersion: apps/v1
    kind: Deployment  #  스케일 아웃할 타겟의 종류 (deployment, replicaset 등)
    name: 3rd-party-app-cancer
  minReplicas: 3  # 최소 replicas 개수
  maxReplicas: 5  # 최대 replicas 개수
  metrics:
  - resource:
      name: cpu  # HPA를 구성할 리소스(CPU, MEM 등)
      targetAverageUtilization: 60  # CPU 사용률이 60% 이상일 경우 생성
    type: Resource  # 리소스 타입 선언
